spring:
  profiles.active: development
  application:
    name: kex
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    open-in-view: false
  mvc:
    log-request-details: 'true'