spring:
  profiles.active: development
  application:
    name: kex
  jpa:
    show-sql: 'false'
    open-in-view: false
  mvc:
    log-request-details: 'true'

logging:
  level:
    org:
      root: WARN
      hibernate: ERROR
      springframework:
        web: DEBUG
      nodeValue: DEBUG
    guru:
      springframework:
        controllers: DEBUG