version: "3.8"

services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: workshop-postgres-db
    environment:
      - POSTGRES_DB=workshop-db
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
    ports:
      - 5432:5432